la_fleur_symfony:
    resource: "@LaFleurSymfonyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
bourse:
    resource: "@LaFleurSymfonyBundle/Resources/config/routing.yml"
    prefix:   /