bourse_homepage:
    path:     /hello/{name}
    defaults: { _controller: BourseBundle:Default:index }
bourse_profile:
    path:     /profile
    defaults: { _controller: BourseBundle:Profile:index }

bourse_connexion :
    path: /connection
    defaults: { _controller: BourseBundle:Profile:connection }
